In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


: means slice

In [10]:
print(arr[4:]) 
print(arr[:4])

[5 6 7]


\- means from back to front

In [12]:
print(arr[-3:-1]) 

[5 6]


[a:b:x]:x means step

In [13]:
print(arr[1:5:2])

[2 4]


row,col for 2d slice

In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [19]:
print(arr[0:2, 2])

[3 8]


In [20]:
print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]
