In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


: means slice

In [3]:
print(arr[4:]) 
print(arr[:4])

[5 6 7]
[1 2 3 4]


\- means from back to front

In [4]:
print(arr[-3:-1]) 

[5 6]


[a:b:x]:x means step

In [5]:
print(arr[1:5:2])

[2 4]


row,col for 2d slice

In [6]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [7]:
print(arr[0:2, 2])

[3 8]


In [8]:
print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


join

In [9]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]


In [10]:
arr = np.stack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [11]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
print(np.vstack((arr1,arr1)))

[[1 2 3]
 [1 2 3]]


In [13]:
print(np.hstack((arr1,arr1)))

[1 2 3 1 2 3]


In [14]:
print(np.dstack((arr1,arr1)))

[[[1 1]
  [2 2]
  [3 3]]]


In [15]:
print(np.concatenate((arr, arr), axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [16]:
np.tile(np.array([0,1,0]),(5,1))

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])